//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWND2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityLog()
        {
            this.ChallengesWon = new HashSet<Challenge>();
        }
    
        public int ActivtyLogId { get; set; }
        public string KidiD { get; set; }
        public int ActivityId { get; set; }
        public int RawScore { get; set; }
        public System.DateTime LogDate { get; set; }
        public decimal Points { get; set; }
        public Nullable<int> ChallengeId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Challenge Challenge { get; set; }
        public virtual KID KID { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Challenge> ChallengesWon { get; set; }
    }
}
