//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWND2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challenge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Challenge()
        {
            this.ActivityLogs = new HashSet<ActivityLog>();
        }
    
        public Nullable<System.TimeSpan> Duration { get; set; }
        public Nullable<int> WinnerId { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int ActivityId { get; set; }
        public int ChallengeId { get; set; }
    
        public virtual Activity Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityLog> ActivityLogs { get; set; }
        public virtual ActivityLog WinningActivityLog { get; set; }
    }
}
